version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Nothing here"

  build:
    commands:
      - echo "Nothing here"

  post_build:
    commands:
      - echo "Updating S3 Bucket..."
      - echo "DONE!!"

artifacts:
  files:
    - index.html
    - index.css
    - apiGateway-js-sdk/
